name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Angka 11
      id: angka-11
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Angka 11
        setup-command: javac Nomor1.java
        command: java Nomor1
        input: '11'
        expected-output: |-
          1 3 5 7 9 11
          1
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Variasi
      id: variasi
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Variasi
        setup-command: javac Nomor2.java
        command: java Nomor2
        input: |-
          3
          Y
          4
          T
        expected-output: |-
          Total voucher belanja : 100000
          Total yang harus dibayar : 595000
        comparison-method: exact
        timeout: 10
        max-score: 40
    - name: Angka 7
      id: angka-7
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Angka 7
        setup-command: javac Nomor1.java
        command: java Nomor1
        input: '7'
        expected-output: |-
          1 3 5 7
          1
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Sesuai Soal
      id: sesuai-soal
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Sesuai Soal
        setup-command: javac Nomor2.java
        command: java Nomor2
        input: |-
          1
          Y
          2
          Y
          4
          N
        expected-output: |-
          Total voucher belanja : 150000
          Total yang harus dibayar : 895000
          3
        comparison-method: exact
        timeout: 10
        max-score: 40
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ANGKA-11_RESULTS: "${{steps.angka-11.outputs.result}}"
        VARIASI_RESULTS: "${{steps.variasi.outputs.result}}"
        ANGKA-7_RESULTS: "${{steps.angka-7.outputs.result}}"
        SESUAI-SOAL_RESULTS: "${{steps.sesuai-soal.outputs.result}}"
      with:
        runners: angka-11,variasi,angka-7,sesuai-soal
